---
title: "MarineGEO Data Submission Report"
output: 
  md_document: 
    variant: markdown
---

#### Report date: `r submission_time`
#### Synthesis status: `r if(report_status()) {"Successful"} else "Failed"`
#### Project affiliation: `r paste(project_affiliation$vector, collapse="; ")`
#### Contact: MarineGEO (marinegeo@si.edu)  

This report documents whether the data submission passes MarineGEO's quality assurance/quality control tests. If your submission failed one of the tests, you can view which protocol and sheet failed the test. Please update your data to fix any errors based on this information. If you cannot determine how to interpret a result, modify your data, or believe your data should be able to pass the tests, email MarineGEO (marinegeo@si.edu). 

Once you've addressed the error(s), resubmit ALL of the data associated with this submission. 

### QA/QC Test Results

Test numeric variables: All data associated with numeric-type columns should either be a numeric value or "NA". If a given sheet fails this test, then a column within that sheet has a character value. Ensure all "NA" values are uppercase. 


```{r, echo=FALSE}

table_length <- nrow(QA_results$df)

# data table of results
datatable(QA_results$df, options = list(pageLength = table_length,
                                     autoWidth = TRUE,
                                     #columnDefs = list(list(width = "47%", targets = c(1,2))),
                                     searching = FALSE,
                                     paging = FALSE))

```

